version: "3.7"

services:
  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    restart: always
